pipeline {
    agent any

    environment {
        IMAGE_V2 = "webapp-devops:v2"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $IMAGE_V2 app/
                '''
            }
        }

        stage('Security Scan') {
            steps {
                sh 'security/trivy-scan.sh'
            }
        }

        stage('Deploy Canary') {
            steps {
                sh 'ansible-playbook -i ansible/inventory.ini ansible/deploy.yml'
            }
        }

        stage('Health Check') {
            steps {
                sh '''
                sleep 20
                curl http://$(minikube ip):30007/health
                '''
            }
        }
    }

    post {
        failure {
            sh 'ansible-playbook -i ansible/inventory.ini ansible/rollback.yml'
        }
    }
}
